import { useState } from 'react'
import { X, Link, Sparkles, Send, FileText, Loader2 } from 'lucide-react'

const PLATFORMS = [
  { id: 'x',         label: 'X',         color: '#1D9BF0' },
  { id: 'linkedin',  label: 'LinkedIn',  color: '#3B82F6' },
  { id: 'instagram', label: 'Instagram', color: '#E1306C' },
]

const PLATFORM_LABELS = { x: 'X', linkedin: 'in', instagram: 'IG' }

export default function CreatePostModal({ onClose, onSave }) {
  const [selectedPlatforms, setSelectedPlatforms] = useState(new Set(['x']))
  const [youtubeUrl, setYoutubeUrl]               = useState('')
  const [content, setContent]                     = useState('')
  const [scheduleDate, setScheduleDate]           = useState('2026-04-20')
  const [scheduleTime, setScheduleTime]           = useState('09:00')
  const [isGenerating, setIsGenerating]           = useState(false)

  const handleSave = () => {
    if (!content.trim()) return
    
    // Pick the first platform as the primary one for the chip
    const primaryPlatform = Array.from(selectedPlatforms)[0]
    
    const newPost = {
      id: Date.now(),
      platform: primaryPlatform,
      date: scheduleDate,
      time: scheduleTime,
      status: 'scheduled',
      content: content,
      engagement: null
    }
    
    onSave(newPost)
  }

  const handleGenerate = async () => {
    if (!youtubeUrl) return
    setIsGenerating(true)
    
    try {
      const response = await fetch(import.meta.env.VITE_N8N_WEBHOOK_URL || '', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          youtubeUrl,
          platforms: Array.from(selectedPlatforms),
          timestamp: new Date().toISOString()
        }),
      })

      if (!response.ok) throw new Error('Generation failed')
      
      const data = await response.json()
      // Expecting { content: "generated text..." }
      setContent(data.content || 'Generation successful, but no content returned.')
    } catch (err) {
      console.error('N8N Error:', err)
      // Fallback for demo if URL is missing
      if (!import.meta.env.VITE_N8N_WEBHOOK_URL) {
        setTimeout(() => {
          setContent("🚀 [DEMO MODE] Connect your n8n webhook in .env.local to see real AI generation!\n\nThis content was generated by a fallback because the VITE_N8N_WEBHOOK_URL is not set.")
        }, 1500)
      } else {
        alert('Failed to connect to n8n. Check console for details.')
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const togglePlatform = (id) => {
    setSelectedPlatforms(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        if (next.size > 1) next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const MAX_CHARS = selectedPlatforms.has('x') ? 280 : 3000
  const remaining = MAX_CHARS - content.length
  const isOverLimit = remaining < 0

  return (
    <div className="modal-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal">
        {/* Header */}
        <div className="modal-header">
          <div>
            <div className="modal-title">Create New Post</div>
            <div className="modal-subtitle">Write manually or generate with AI from a YouTube video</div>
          </div>
          <button className="modal-close" onClick={onClose}>
            <X size={16} />
          </button>
        </div>

        {/* Body */}
        <div className="modal-body">

          {/* Platform picker */}
          <div>
            <div className="modal-section-label">Publish to</div>
            <div className="platform-picker">
              {PLATFORMS.map(({ id, label, color }) => {
                const isSelected = selectedPlatforms.has(id)
                return (
                  <button
                    key={id}
                    className={`platform-pick-btn ${isSelected ? `selected-${id}` : ''}`}
                    onClick={() => togglePlatform(id)}
                  >
                    <span
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        width: 18,
                        height: 18,
                        borderRadius: 4,
                        background: isSelected ? `${color}22` : 'rgba(255,255,255,0.04)',
                        color: isSelected ? color : 'var(--text-muted)',
                        fontSize: 9,
                        fontWeight: 800,
                        fontFamily: 'var(--font-display)',
                      }}
                    >
                      {PLATFORM_LABELS[id]}
                    </span>
                    {label}
                  </button>
                )
              })}
            </div>
          </div>

          {/* YouTube URL */}
          <div>
            <div className="modal-section-label">AI Source (optional)</div>
            <div className="source-input-wrap">
              <input
                className="source-input"
                type="url"
                placeholder="Paste a YouTube URL to generate content with Claude…"
                value={youtubeUrl}
                onChange={e => setYoutubeUrl(e.target.value)}
              />
              <span className="source-input-icon">
                <Link size={14} />
              </span>
            </div>
            <button
              className="ai-generate-btn"
              style={{ marginTop: 8 }}
              disabled={!youtubeUrl || isGenerating}
              onClick={handleGenerate}
            >
              {isGenerating ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
              {isGenerating ? 'Claude is thinking...' : 'Generate posts with Claude'}
              <span style={{ marginLeft: 'auto', fontSize: 10, opacity: 0.6, fontWeight: 400 }}>
                via n8n API
              </span>
            </button>
          </div>

          {/* Divider */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            color: 'var(--text-muted)',
            fontSize: 11,
          }}>
            <div style={{ flex: 1, height: 1, background: 'var(--border-subtle)' }} />
            or write manually
            <div style={{ flex: 1, height: 1, background: 'var(--border-subtle)' }} />
          </div>

          {/* Content */}
          <div>
            <div className="modal-section-label">Post Content</div>
            <div className="content-area">
              <textarea
                className="content-textarea"
                placeholder="What do you want to share? Hook first, substance second, CTA last…"
                value={content}
                onChange={e => setContent(e.target.value)}
              />
              <span
                className="char-count"
                style={{ color: isOverLimit ? '#EF4444' : undefined }}
              >
                {remaining < 0 ? `${Math.abs(remaining)} over` : `${remaining} left`}
              </span>
            </div>
          </div>

          {/* Schedule */}
          <div>
            <div className="modal-section-label">Schedule</div>
            <div className="datetime-row">
              <input
                type="date"
                className="datetime-input"
                value={scheduleDate}
                onChange={e => setScheduleDate(e.target.value)}
              />
              <input
                type="time"
                className="datetime-input"
                value={scheduleTime}
                onChange={e => setScheduleTime(e.target.value)}
              />
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="modal-footer">
          <button className="modal-btn-secondary" onClick={onClose}>
            <FileText size={13} style={{ marginRight: 5 }} />
            Save Draft
          </button>
          <button 
            className="modal-btn-primary" 
            disabled={!content.trim()}
            onClick={handleSave}
          >
            <Send size={13} />
            Schedule Post
          </button>
        </div>
      </div>
    </div>
  )
}
